name: Cypress Tests

on: push
jobs:
  cypress_tests:
    strategy:
      matrix:
        include:
          - spec: 'cypress/e2e/desktop/*.cy.ts'
            config_file: 'cypress.config.ts'
          - spec: 'cypress/e2e/mobile/*.cy.ts'
            config_file: 'cypress.mobile.config.ts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start:cypress
          browser: chrome
          spec: ${{ matrix.spec }}
          config-file: ${{ matrix.config_file }}
      - name: Upload videos of failed tests
        uses: actions/upload-artifact@v4
        if: always() # ensures this step runs even if tests fail
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7 # Optional: how long to keep artifacts
