name: Cypress Tests

on: [workflow_call]

jobs:
  cypress_tests:
    strategy:
      matrix:
        include:
          - spec: 'cypress/e2e/desktop/*.cy.ts'
            config_file: 'cypress.config.mjs'
          - spec: 'cypress/e2e/mobile/*.cy.ts'
            config_file: 'cypress.mobile.config.mjs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start:cypress
          browser: chrome
          spec: ${{ matrix.spec }}
          config-file: ${{ matrix.config_file }}
