name: Lighthouse Test

on: [workflow_call]
env:
  AWS_DEFAULT_REGION: us-east-2
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts/lighthouse/${{ github.sha }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/test-access
          role-session-name: github-${{ github.sha }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: ${{ github.workspace }}/tmp/artifacts/lighthouse/${{ github.sha }}
          urls: https://test.phlask.me/${{ github.sha }}/
      - name: Upload Lighthouse Test Result to S3
        run: |
          mv ${GITHUB_WORKSPACE}/tmp/artifacts/lighthouse/${GITHUB_SHA}/report-*.html ${GITHUB_WORKSPACE}/tmp/artifacts/lighthouse/${GITHUB_SHA}/lighthouse_result.html
          aws s3 cp ${GITHUB_WORKSPACE}/tmp/artifacts/lighthouse/${GITHUB_SHA}/lighthouse_result.html s3://test.phlask.me/${GITHUB_SHA}/testResults/lighthouse_result.html
          aws --region us-east-1 dynamodb update-item --table-name test-page-list --key '{
            "gitHash": {"S": "'${GITHUB_SHA}'"}
          }' --update-expression "SET #G = :g" --expression-attribute-names '{
            "#G": "lighthouseTestAvailable"
          }' --expression-attribute-values '{
            ":g":{"S": "true"}
          }'
